import dotenvFlow from "dotenv-flow";

dotenvFlow.config();

const {
	PORT,
	NODE_ENV,
	SALT_ROUNDS,
	REFRESH_TOKEN_SECRET,
	JWKS_URI,
	MAIN_DOMAIN,
	CLIENT_UI_DOMAIN,
	JWT_KEY_ID,
	GOOGLE_OAUTH_URL,
	GOOGLE_CLIENT_ID,
	GOOGLE_CLIENT_SECRET,
	GOOGLE_ACCESS_TOKEN_URL,
	GOOGLE_TOKEN_INFO_URL,
	GOOGLE_CALLBACK_URL,
} = process.env;

export const Config = {
	PORT: Number(PORT),
	NODE_ENV: NODE_ENV,
	SALT_ROUNDS: Number(SALT_ROUNDS),
	REFRESH_TOKEN_SECRET,
	JWKS_URI,
	JWT_KEY_ID,
	MAIN_DOMAIN,
	CLIENT_UI_DOMAIN,
	GOOGLE_OAUTH_URL,
	GOOGLE_CLIENT_ID,
	GOOGLE_CLIENT_SECRET,
	GOOGLE_ACCESS_TOKEN_URL,
	GOOGLE_TOKEN_INFO_URL,
	GOOGLE_CALLBACK_URL,
};
